#!/command/with-contenv sh
cd /app/bff
export DOTENV_PRIVATE_KEY="${DOTENV_PRIVATE_KEY_BFF:-}"
export BFF_PORT="${BFF_PORT:-3002}"
export API_URL="${API_URL:-http://localhost:3001}"
exec s6-setuidgid nodejs dotenvx run --env-file=.env.production -- node dist/index.js
