#!/command/with-contenv sh
cd /app/api
export DOTENV_PRIVATE_KEY="${DOTENV_PRIVATE_KEY_API:-}"
export API_PORT="${API_PORT:-3001}"
exec s6-setuidgid nodejs dotenvx run --env-file=.env.production -- node dist/index.js
